/* javascriptcore-3.0.vapi generated by vapigen, do not modify. */

[CCode (cprefix = "JS", gir_namespace = "JavaScriptCore", gir_version = "3.0", lower_case_cprefix = "JS_")]
namespace JS {
	[CCode (cheader_filename = "JavaScriptCore-3.0.h", cname = "JSGlobalContextRef", has_type_id = false)]
	public struct GlobalContext {
	}
	[CCode (cheader_filename = "JavaScriptCore-3.0.h", cname = "JSValueRef", has_type_id = false)]
	public struct Value {
	}
}
