/*
 * Generated by gdbus-codegen 2.34.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __GSSO_UI_DIALOG_DBUS_GLUE_H__
#define __GSSO_UI_DIALOG_DBUS_GLUE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.google.code.AccountsSSO.gSingleSignOn.UI.Dialog */

#define SSO_DBUS_TYPE_UIDIALOG (sso_dbus_uidialog_get_type ())
#define SSO_DBUS_UIDIALOG(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SSO_DBUS_TYPE_UIDIALOG, SSODbusUIDialog))
#define SSO_DBUS_IS_UIDIALOG(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SSO_DBUS_TYPE_UIDIALOG))
#define SSO_DBUS_UIDIALOG_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), SSO_DBUS_TYPE_UIDIALOG, SSODbusUIDialogIface))

struct _SSODbusUIDialog;
typedef struct _SSODbusUIDialog SSODbusUIDialog;
typedef struct _SSODbusUIDialogIface SSODbusUIDialogIface;

struct _SSODbusUIDialogIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_cancel_ui_request) (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_request_id);

  gboolean (*handle_query_dialog) (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_parameters);

  gboolean (*handle_refresh_dialog) (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_parameters);

  void (*refresh) (
    SSODbusUIDialog *object,
    const gchar *arg_request_id);

};

GType sso_dbus_uidialog_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *sso_dbus_uidialog_interface_info (void);
guint sso_dbus_uidialog_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void sso_dbus_uidialog_complete_query_dialog (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation,
    GVariant *return_value);

void sso_dbus_uidialog_complete_refresh_dialog (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation);

void sso_dbus_uidialog_complete_cancel_ui_request (
    SSODbusUIDialog *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void sso_dbus_uidialog_emit_refresh (
    SSODbusUIDialog *object,
    const gchar *arg_request_id);



/* D-Bus method calls: */
void sso_dbus_uidialog_call_query_dialog (
    SSODbusUIDialog *proxy,
    GVariant *arg_parameters,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean sso_dbus_uidialog_call_query_dialog_finish (
    SSODbusUIDialog *proxy,
    GVariant **out_return_value,
    GAsyncResult *res,
    GError **error);

gboolean sso_dbus_uidialog_call_query_dialog_sync (
    SSODbusUIDialog *proxy,
    GVariant *arg_parameters,
    GVariant **out_return_value,
    GCancellable *cancellable,
    GError **error);

void sso_dbus_uidialog_call_refresh_dialog (
    SSODbusUIDialog *proxy,
    GVariant *arg_parameters,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean sso_dbus_uidialog_call_refresh_dialog_finish (
    SSODbusUIDialog *proxy,
    GAsyncResult *res,
    GError **error);

gboolean sso_dbus_uidialog_call_refresh_dialog_sync (
    SSODbusUIDialog *proxy,
    GVariant *arg_parameters,
    GCancellable *cancellable,
    GError **error);

void sso_dbus_uidialog_call_cancel_ui_request (
    SSODbusUIDialog *proxy,
    const gchar *arg_request_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean sso_dbus_uidialog_call_cancel_ui_request_finish (
    SSODbusUIDialog *proxy,
    GAsyncResult *res,
    GError **error);

gboolean sso_dbus_uidialog_call_cancel_ui_request_sync (
    SSODbusUIDialog *proxy,
    const gchar *arg_request_id,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define SSO_DBUS_TYPE_UIDIALOG_PROXY (sso_dbus_uidialog_proxy_get_type ())
#define SSO_DBUS_UIDIALOG_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SSO_DBUS_TYPE_UIDIALOG_PROXY, SSODbusUIDialogProxy))
#define SSO_DBUS_UIDIALOG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SSO_DBUS_TYPE_UIDIALOG_PROXY, SSODbusUIDialogProxyClass))
#define SSO_DBUS_UIDIALOG_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SSO_DBUS_TYPE_UIDIALOG_PROXY, SSODbusUIDialogProxyClass))
#define SSO_DBUS_IS_UIDIALOG_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SSO_DBUS_TYPE_UIDIALOG_PROXY))
#define SSO_DBUS_IS_UIDIALOG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SSO_DBUS_TYPE_UIDIALOG_PROXY))

typedef struct _SSODbusUIDialogProxy SSODbusUIDialogProxy;
typedef struct _SSODbusUIDialogProxyClass SSODbusUIDialogProxyClass;
typedef struct _SSODbusUIDialogProxyPrivate SSODbusUIDialogProxyPrivate;

struct _SSODbusUIDialogProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  SSODbusUIDialogProxyPrivate *priv;
};

struct _SSODbusUIDialogProxyClass
{
  GDBusProxyClass parent_class;
};

GType sso_dbus_uidialog_proxy_get_type (void) G_GNUC_CONST;

void sso_dbus_uidialog_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SSODbusUIDialog *sso_dbus_uidialog_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
SSODbusUIDialog *sso_dbus_uidialog_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void sso_dbus_uidialog_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
SSODbusUIDialog *sso_dbus_uidialog_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
SSODbusUIDialog *sso_dbus_uidialog_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define SSO_DBUS_TYPE_UIDIALOG_SKELETON (sso_dbus_uidialog_skeleton_get_type ())
#define SSO_DBUS_UIDIALOG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), SSO_DBUS_TYPE_UIDIALOG_SKELETON, SSODbusUIDialogSkeleton))
#define SSO_DBUS_UIDIALOG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), SSO_DBUS_TYPE_UIDIALOG_SKELETON, SSODbusUIDialogSkeletonClass))
#define SSO_DBUS_UIDIALOG_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), SSO_DBUS_TYPE_UIDIALOG_SKELETON, SSODbusUIDialogSkeletonClass))
#define SSO_DBUS_IS_UIDIALOG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), SSO_DBUS_TYPE_UIDIALOG_SKELETON))
#define SSO_DBUS_IS_UIDIALOG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), SSO_DBUS_TYPE_UIDIALOG_SKELETON))

typedef struct _SSODbusUIDialogSkeleton SSODbusUIDialogSkeleton;
typedef struct _SSODbusUIDialogSkeletonClass SSODbusUIDialogSkeletonClass;
typedef struct _SSODbusUIDialogSkeletonPrivate SSODbusUIDialogSkeletonPrivate;

struct _SSODbusUIDialogSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  SSODbusUIDialogSkeletonPrivate *priv;
};

struct _SSODbusUIDialogSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType sso_dbus_uidialog_skeleton_get_type (void) G_GNUC_CONST;

SSODbusUIDialog *sso_dbus_uidialog_skeleton_new (void);


G_END_DECLS

#endif /* __GSSO_UI_DIALOG_DBUS_GLUE_H__ */
